branches:
  only:
    - master
    - develop

install:
  - set QTDIR=C:\Qt\5.10.0\msvc2015
  ### - choco install -y InnoSetup
  - ps: Start-FileDownload 'http://www.jrsoftware.org/download.php/is.exe' is.exe
  - is.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-
  - set PATH=%QTDIR%\bin;%PATH%;"C:\Program Files (x86)\Inno Setup 5"
  
build_script:
  - git submodule update --init --recursive
  - qmake source\dana.pro CONFIG+=release
  - cd source && make
  
after_build:
  - windeployqt release/dana.exe
  - cmd: cp LICENSE release/LICENSE.txt
  - rm release/*.o
  - rm release/*.cpp
  - rm release/*.h
  - iscc ./installer/installer.iss

artifacts:
 - path: Output/dana-*.exe
   name: SetupExe

deploy:
 provider: GitHub
 on:
   appveyor_repo_tag: true
 auth_token:
    secure: DsQ/Nv6Df/ryOXUJhBBmDJFwZ6HHGaIauruGGnv4ouuhw9P6necvd8jjKohav/7Y
 artifact: SetupExe
 prerelease: true
 tag: $(APPVEYOR_REPO_TAG_NAME)
 release: $(APPVEYOR_REPO_TAG_NAME)
 description: $(APPVEYOR_REPO_COMMIT_MESSAGE)

