language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt591-trusty -y
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt59base qt59svg qt59charts-no-lgpl
  - sudo apt-get install -qq festival-dev
  - source /opt/qt59/bin/qt59-env.sh
  

# Build steps
script:
  - cd source
  - qmake 
  - make
