sudo: required
before_install:
  - sudo apt-get install festival-dev
  
# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc
  

# Build steps
script:
  - mkdir build
  - cd build
  - qmake .. && make
