language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt593-trusty -y
  - sudo apt-get update -qq
  
install:
  - sudo apt-get -y install qt59base qt59svg qt59charts-no-lgpl qt59speech
  - source /opt/qt59/bin/qt59-env.sh
  

# Build steps
script:
  - cd source
  - qmake CONFIG+=release PREFIX=/usr
  - make -j$(nproc)
  - make INSTALL_ROOT=appdir -j$(nproc) install ; find appdir/
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
  - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage

after_success:
  # echo "TRAVIS_TAG is " ${TRAVIS_TAG};
  - export UPLOADTOOL_SUFFIX=${TRAVIS_TAG}
  # if TRAVIS_TAG is empty, no need to release anything
  - if [ ! -z "${TRAVIS_TAG}" ]; then find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq; fi;
  - if [ ! -z "${TRAVIS_TAG}" ]; then curl --upload-file Dana*.AppImage https://transfer.sh/APPNAME-${TRAVIS_TAG}-linux.AppImage; fi;
  - if [ ! -z "${TRAVIS_TAG}" ]; then wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh; fi;
  - if [ ! -z "${TRAVIS_TAG}" ]; then bash upload.sh Dana*.AppImage*; fi;
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
