language: cpp
compiler: gcc
sudo: require
dist: trusty

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "qZ4QgU11evsgCp7UQ9EGrDhod27jfv18MLiEhrkOf1f7ERyi5oxSN4iU5D2k2Qhe7Y76C46DpxxcXvV/DGg86eTM+wTO2B0CdtvSoKW4U/bTjRpIN93uIfrPlCkHrUcXgcCnyYBoUdSuRKQa9ijys7LOzqlVXEfXaCz4306tZksbA36+8ut2aalr/+7mtvsWD7iVgudk3l6+A+Lf5bIW9Bs3h8tqXpdtVSP9VV3pW+UoS85Co9l9vAsJd7qoWgrshVDT8ePIykDFI+YjMReweQ+gakcW4I4p9VjI6/zUURE0K6wjQe3+UZyCyKwxc8CNGAcvUlJPwLd0VWNYap+LvCrGZwAqu2QQbus0fLJAtyJoqSwyuoP5jHPflBZO3jgyJPRFFRvBF83J2ck3P1HZ4firHmyLYWwwpI8nqzfEfyJ/qpWe53Tqmv8T63qOIiVvkj1g+T373ABnvjbqGv2nnCWuP+BE7xqK0Jyz9E8DVw3H7lhhiKM+RXw4CvFjjNJnpbKvYRogAEirioIrH8YjBiSPYe9tNaXLuf/quIEdPnTssF+ig9DZ7xNdlGLIjMaZjIfCdbUwicBWYbShMga9ysc/Ba0sH1hcxxyczDEgmY3/zL7y/cjOrGDGnW9B44FmQ7JO6ZY6zPzvmUG78y7bAQPJtoVelXHWjJBt5Qip3hg="

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt593-trusty -y
  - sudo apt-get update -qq
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "m-o-s-t-a-f-a/dana"
      description: "Build submitted via Travis CI"
    notification_email: mostafa.sedaghat@gmail.com
    build_command_prepend: "make clean"
    build_command: "make -j$(nproc)"
    branch_pattern: coverity_scan
    
install:
  - sudo apt-get -y install qt59base qt59svg qt59charts-no-lgpl qt59speech
  - source /opt/qt59/bin/qt59-env.sh
  

# Build steps
script:
  - cd source
  - qmake CONFIG+=release PREFIX=/usr
  - make -j$(nproc)
  - make INSTALL_ROOT=appdir -j$(nproc) install ; find appdir/
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
  - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage

after_success:
  - # echo "TRAVIS_TAG is " ${TRAVIS_TAG};
  - export UPLOADTOOL_SUFFIX=${TRAVIS_TAG}
  - # if TRAVIS_TAG is empty, no need to release anything
  - if [ ! -z "${TRAVIS_TAG}" ]; find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq; fi;
  - if [ ! -z "${TRAVIS_TAG}" ]; curl --upload-file Dana*.AppImage https://transfer.sh/APPNAME-${TRAVIS_TAG}-linux.AppImage; fi;
  - if [ ! -z "${TRAVIS_TAG}" ]; wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh; fi;
  - if [ ! -z "${TRAVIS_TAG}" ]; bash upload.sh Dana*.AppImage*; fi;
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
