sudo: required

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y
  - sudo apt-get update

install:
  - sudo apt-get install qt58base qt58svg
  - source /opt/qt58/bin/qt58-env.sh
  - sudo apt-get install -qq festival-dev
  
# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc
  

# Build steps
script:
  - cd source
  - /opt/qt58/bin/qmake 
  - make
